services:


  db: #сервис базы данных для wordpress
   image: mariadb:12.3.2 #докер образ из которого будет создан контейнер mariadb

   environment: #переменные окружения которые передаются внутрь контейнера mariadb
     MARIADB_DATABASE: ${DB_NAME}
     MARIADB_USER: ${DB_USER}
     MARIADB_PASSWORD: ${DB_PASSWORD}
     MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

   volumes: #постоянное хранилище базы данных
     - db_data:/var/lib/mysql

   healthcheck:
     test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
     interval: 10s
     timeout: 5s
     retries: 5



  wordpress: #само веб приложение 
   image: wordpress:7.0.2

   restart: unless-stopped

   depends_on:
     db:
       condition: service_healthy

  
   healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost/"]
     interval: 10s
     timeout: 5s
     retries: 5
    

   environment: #данные для подключения Wordpress к MariaDb
     WORDPRESS_DB_HOST: db:3306 #стандартный порт mysql/mariadb
     WORDPRESS_DB_NAME: ${DB_NAME}
     WORDPRESS_DB_USER: ${DB_USER}
     WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
   
   volumes: #постоянное хранилище файлов wordpress
     - wordpress_data:/var/www/html 




  nginx:
   image: nginx:stable

   restart: unless-stopped

   depends_on:
     - wordpress

   healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost/"]
     interval: 10s
     timeout: 5s
     retries: 5

   ports:
     - "80:80"
     - "443:443"

   volumes: 
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro #read-only
     - ./nginx/ssl:/etc/nginx/ssl:ro



  prometheus:
   image: prom/prometheus:latest

   restart: unless-stopped


   volumes:
     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
     - prometheus_data:/prometheus



  grafana:
    image: grafana/grafana:latest

    restart: unless-stopped


    depends_on:
      - prometheus

    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana_data:/var/lib/grafana



  node_exporter:
    image: prom/node-exporter:latest

    restart: unless-stopped


    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'






volumes:
  db_data: #данные mariadb
  wordpress_data: #файлы wordpress
  prometheus_data:
  grafana_data: 
