#основные настройки Nginx

events {
    worker_connections 1024;
}

http {
    server{
        listen 80;

        server_name site.local; #wordpress


        location = /wp-login.php {
            allow 192.168.31.162;
            deny all;

            proxy_pass http://wordpress:80;

            proxy_set_header Host $http_host;

            proxy_set_header X-Real-IP $remote_addr;

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_set_header X-Forwarded-Proto $scheme;


        }


        location ^~ /wp-admin/ {
            allow 192.168.31.162;
            deny all;

            proxy_pass http://wordpress:80;

            proxy_set_header Host $http_host;

            proxy_set_header X-Real-IP $remote_addr;

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_set_header X-Forwarded-Proto $scheme;
        }

        
        location / {
            proxy_pass http://wordpress:80;

            proxy_set_header Host $http_host;

            proxy_set_header X-Real-IP $remote_addr;

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_set_header X-Forwarded-Proto $scheme;

        }



    }

        server{
            listen 443 ssl;

            server_name site.local;

            ssl_certificate /etc/nginx/ssl/site.local.crt;
            ssl_certificate_key /etc/nginx/ssl/site.local.key;

            location = /wp-login.php {
            allow 192.168.31.162;
            deny all;

            proxy_pass http://wordpress:80;

            proxy_set_header Host $http_host;

            proxy_set_header X-Real-IP $remote_addr;

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_set_header X-Forwarded-Proto $scheme;


        }


            location ^~ /wp-admin/ {
            allow 192.168.31.162;
            deny all;

            proxy_pass http://wordpress:80;

            proxy_set_header Host $http_host;

            proxy_set_header X-Real-IP $remote_addr;

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_set_header X-Forwarded-Proto $scheme;
        }



            


            location / {
            proxy_pass http://wordpress:80;

            proxy_set_header Host $http_host;

            proxy_set_header X-Real-IP $remote_addr;

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_set_header X-Forwarded-Proto $scheme;
                
            }

        }

        server{
            listen 80;

            server_name metrics.local;

            location / {
                proxy_pass http://grafana:3000;

                proxy_set_header Host $http_host;

                proxy_set_header X-Real-IP $remote_addr;

                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                proxy_set_header X-Forwarded-Proto $scheme;


            }

        }
    
}